backend:
    name: git-gateway
    branch: master

publish_mode: editorial_workflow
media_folder: /res/img

collections:
    - name: "post"
      label: "Post"
      folder: "_posts"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "post", required: true}
          - {label: "Title", name: "title", widget: "string", required: true}
          - {label: "Author", name: "author", widget: "string", required: true}
          - {label: "Tags", name: "tags", widget: "string", required: false}
          - {label: "Thumbnail Image", name: "thumbnail", widget: "image", required: false}
          - {label: "Banner Image", name: "banner", widget: "image", required: false}
          - {label: "Summary", name: "summary", widget: "string", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Should appear in the 'News & Events' section of the home page?", name: "isNews", widget: "boolean", default: false, required: false}
